CREATE TABLE public.nodes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  nm character varying NOT NULL,
  CONSTRAINT nodes_pkey PRIMARY KEY (id)
);

ALTER TABLE public.nodes ENABLE ROW LEVEL SECURITY;

CREATE POLICY nodes_anon_select ON public.nodes
  FOR SELECT TO anon
  USING (true);
